(function(angular){
  angular.module('ngAtomSpinner')
  .directive('atomSpinner', [
    function(){
      return {
        restrict: 'EA',
        scope: {},
        template: '<style>.ng-atom-spinner{width:100px;height:100px;margin:50px auto;position:relative;}.ngAS-ball-1{height:50%;width:50%;left:50%;top:50%;position:absolute;z-index:1;-webkit-animation:shrink 4.5s infinite linear;animation:shrink 4.5s infinite linear;}.ngAS-ball-1:before{content:"";background:#7db9e8;border-radius:50%;height:100%;width:100%;position:absolute;top:-50%;left:-50%;}.ngAS-ball-2,.ngAS-ball-3,.ngAS-ball-4{position:absolute;width:100%;height:100%;z-index:0;}.ngAS-ball-2:before,.ngAS-ball-3:before,.ngAS-ball-4:before{content:"";height:20px;width:20px;border-radius:50%;background:#333;top:0;left:0;margin:0 auto;position:absolute;}.ngAS-ball-2{-webkit-animation:zindex 1.5s 0.75s infinite steps(2, end);animation:zindex 1.5s 0.75s infinite steps(2, end);}.ngAS-ball-3{-webkit-transform:rotate(120deg);transform:rotate(120deg);-webkit-animation:zindex 1.5s -0.25s infinite steps(2, end);animation:zindex 1.5s -0.25s infinite steps(2, end);}.ngAS-ball-4{-webkit-transform:rotate(240deg);transform:rotate(240deg);-webkit-animation:zindex 1.5s 0.25s infinite steps(2, end);animation:zindex 1.5s 0.25s infinite steps(2, end);}.ngAS-ball-2:before{-webkit-transform:rotate(0);transform:rotate(0);'+
        '-webkit-animation:position 1.5s infinite ease, size 1.5s -1.125s infinite ease;animation:position 1.5s infinite ease, size 1.5s -1.125s infinite ease;}.ngAS-ball-3:before{-webkit-animation:position 1.5s -1s infinite ease, size 1.5s -0.75s infinite ease;animation:position 1.5s -1s infinite ease, size 1.5s -0.75s infinite ease;}.ngAS-ball-4:before{-webkit-animation:position 1.5s -0.5s infinite ease, size 1.5s -0.125s infinite ease;animation:position 1.5s -0.5s infinite ease, size 1.5s -0.125s infinite ease;}@-webkit-keyframes position{50%{top:80px;left:80px;}}@keyframes position{50%{top:80px;left:80px;}}@-webkit-keyframes size{50%{-webkit-transform:scale(0.5, 0.5);transform:scale(0.5, 0.5);}}@keyframes size{50%{-webkit-transform:scale(0.5, 0.5);transform:scale(0.5, 0.5);}}@-webkit-keyframes zindex{100%{z-index:10;}}@keyframes zindex{100%{z-index:10;}}@-webkit-keyframes shrink{50%{-webkit-transform:scale(0.9, 0.9);transform:scale(0.9, 0.9);}}@keyframes shrink{50%{-webkit-transform:scale(0.9, 0.9);transform:scale(0.9, 0.9);}}</style><div class="ng-atom-spinner"><div class="ngAS-ball ngAS-ball-1"></div><div class="ngAS-ball ngAS-ball-2"></div><div class="ngAS-ball ngAS-ball-3"></div><div class="ngAS-ball ngAS-ball-4"></div></div>';
      };
    }
  ])
})(window.angular)
